In [65]:
import pandas as pd
import numpy as np

In [66]:
def generate_dates(start_date, end_date, n, unit):
    diff_days = (end_date - start_date).days + 1 
    return pd.date_range(start = start_date, end = end_date )

In [67]:
def shuffle_rows(df):
    return  df.sample(frac=1)

In [68]:
np.random.seed(0)
start_date = pd.to_datetime('2021-01-01')
end_date = pd.to_datetime('2021-12-31')
n = 10

In [69]:
dates = generate_dates(start_date=start_date, 
                       end_date=end_date,
                       n=n,
                       unit='D' )

In [70]:
df= pd.DataFrame(dates,columns=['Dates'])
df.info

<bound method DataFrame.info of          Dates
0   2021-01-01
1   2021-01-02
2   2021-01-03
3   2021-01-04
4   2021-01-05
5   2021-01-06
6   2021-01-07
7   2021-01-08
8   2021-01-09
9   2021-01-10
10  2021-01-11
11  2021-01-12
12  2021-01-13
13  2021-01-14
14  2021-01-15
15  2021-01-16
16  2021-01-17
17  2021-01-18
18  2021-01-19
19  2021-01-20
20  2021-01-21
21  2021-01-22
22  2021-01-23
23  2021-01-24
24  2021-01-25
25  2021-01-26
26  2021-01-27
27  2021-01-28
28  2021-01-29
29  2021-01-30
..         ...
335 2021-12-02
336 2021-12-03
337 2021-12-04
338 2021-12-05
339 2021-12-06
340 2021-12-07
341 2021-12-08
342 2021-12-09
343 2021-12-10
344 2021-12-11
345 2021-12-12
346 2021-12-13
347 2021-12-14
348 2021-12-15
349 2021-12-16
350 2021-12-17
351 2021-12-18
352 2021-12-19
353 2021-12-20
354 2021-12-21
355 2021-12-22
356 2021-12-23
357 2021-12-24
358 2021-12-25
359 2021-12-26
360 2021-12-27
361 2021-12-28
362 2021-12-29
363 2021-12-30
364 2021-12-31

[365 rows x 1 columns]>

In [75]:
df2 = shuffle_rows(df=df)
df2.info

<bound method DataFrame.info of          Dates
150 2021-05-31
357 2021-12-24
130 2021-05-11
59  2021-03-01
317 2021-11-14
16  2021-01-17
110 2021-04-21
316 2021-11-13
14  2021-01-15
325 2021-11-22
139 2021-05-20
355 2021-12-22
323 2021-11-20
339 2021-12-06
315 2021-11-12
344 2021-12-11
230 2021-08-19
31  2021-02-01
232 2021-08-21
40  2021-02-10
303 2021-10-31
55  2021-02-25
11  2021-01-12
346 2021-12-13
333 2021-11-30
67  2021-03-09
329 2021-11-26
313 2021-11-10
1   2021-01-02
124 2021-05-05
..         ...
185 2021-07-05
276 2021-10-04
153 2021-06-03
54  2021-02-24
30  2021-01-31
305 2021-11-02
100 2021-04-11
4   2021-01-05
280 2021-10-08
151 2021-06-01
237 2021-08-26
56  2021-02-26
60  2021-03-02
209 2021-07-29
262 2021-09-20
227 2021-08-16
264 2021-09-22
335 2021-12-02
22  2021-01-23
208 2021-07-28
13  2021-01-14
136 2021-05-17
167 2021-06-17
38  2021-02-08
326 2021-11-23
269 2021-09-27
300 2021-10-28
201 2021-07-21
106 2021-04-17
58  2021-02-28

[365 rows x 1 columns]>

In [78]:
import random
val_start = 0.5
val_end = 90
df2['Values'] = [ random.uniform(val_start, val_end) for k in df2.index]

In [79]:
df2.info

<bound method DataFrame.info of          Dates     Values
150 2021-05-31  26.566076
357 2021-12-24  48.511940
130 2021-05-11  88.371997
59  2021-03-01  61.832619
317 2021-11-14  12.362831
16  2021-01-17  60.397891
110 2021-04-21  58.549386
316 2021-11-13  39.205583
14  2021-01-15  23.846101
325 2021-11-22  37.668896
139 2021-05-20  23.758545
355 2021-12-22  41.149203
323 2021-11-20   6.677134
339 2021-12-06  48.782145
315 2021-11-12  75.565147
344 2021-12-11  36.465762
230 2021-08-19  53.764532
31  2021-02-01  71.250621
232 2021-08-21  44.152576
40  2021-02-10   6.603030
303 2021-10-31  66.070474
55  2021-02-25  49.700514
11  2021-01-12  45.996432
346 2021-12-13  23.471898
333 2021-11-30  65.531116
67  2021-03-09  30.185123
329 2021-11-26  26.053920
313 2021-11-10  34.857227
1   2021-01-02  42.595000
124 2021-05-05   9.946298
..         ...        ...
185 2021-07-05  59.898466
276 2021-10-04  40.785383
153 2021-06-03  38.037143
54  2021-02-24   0.718327
30  2021-01-31  63.236411
305 2021-11-02  42.126827
100 2021-04-11  29.226261
4   2021-01-05  68.024991
280 2021-10-08   1.818287
151 2021-06-01   3.803936
237 2021-08-26  86.847767
56  2021-02-26  61.123274
60  2021-03-02  41.030469
209 2021-07-29  18.589427
262 2021-09-20  46.553528
227 2021-08-16  82.084616
264 2021-09-22  61.565287
335 2021-12-02  41.910147
22  2021-01-23  83.411220
208 2021-07-28  68.058655
13  2021-01-14   7.859031
136 2021-05-17  15.376506
167 2021-06-17  80.696962
38  2021-02-08  71.985940
326 2021-11-23  53.627604
269 2021-09-27  51.538804
300 2021-10-28   1.936509
201 2021-07-21   6.778653
106 2021-04-17  52.584850
58  2021-02-28  62.221112

[365 rows x 2 columns]>

In [80]:
df2.to_excel("synthetic_data_output.xlsx")