In [145]:
import pandas as pd
import numpy as np

In [146]:
def generate_dates(start_date, end_date, n, unit):
    diff_days = (end_date - start_date).days + 1 
    return pd.date_range(start = start_date, end = end_date )

In [147]:
def shuffle_rows(df):
    return  df.sample(frac=1)

In [148]:
np.random.seed(0)
start_date = pd.to_datetime('2021-01-01')
end_date = pd.to_datetime('2021-12-31')
n = 10

In [149]:
dates = generate_dates(start_date=start_date, 
                              end_date=end_date,
                              n=n,
                              unit='D' )
df = pd.DataFrame(dates)
print(df)
df2 = shuffle_rows(df=df)

print(df2)

             0
0   2021-01-01
1   2021-01-02
2   2021-01-03
3   2021-01-04
4   2021-01-05
5   2021-01-06
6   2021-01-07
7   2021-01-08
8   2021-01-09
9   2021-01-10
10  2021-01-11
11  2021-01-12
12  2021-01-13
13  2021-01-14
14  2021-01-15
15  2021-01-16
16  2021-01-17
17  2021-01-18
18  2021-01-19
19  2021-01-20
20  2021-01-21
21  2021-01-22
22  2021-01-23
23  2021-01-24
24  2021-01-25
25  2021-01-26
26  2021-01-27
27  2021-01-28
28  2021-01-29
29  2021-01-30
..         ...
335 2021-12-02
336 2021-12-03
337 2021-12-04
338 2021-12-05
339 2021-12-06
340 2021-12-07
341 2021-12-08
342 2021-12-09
343 2021-12-10
344 2021-12-11
345 2021-12-12
346 2021-12-13
347 2021-12-14
348 2021-12-15
349 2021-12-16
350 2021-12-17
351 2021-12-18
352 2021-12-19
353 2021-12-20
354 2021-12-21
355 2021-12-22
356 2021-12-23
357 2021-12-24
358 2021-12-25
359 2021-12-26
360 2021-12-27
361 2021-12-28
362 2021-12-29
363 2021-12-30
364 2021-12-31

[365 rows x 1 columns]
             0
106 2021-04-17
259 2021-09-17
45  2021-02-15
26  2021-01-27
78  2021-03-20
346 2021-12-13
90  2021-04-01
311 2021-11-08
239 2021-08-28
6   2021-01-07
120 2021-05-01
141 2021-05-22
263 2021-09-21
286 2021-10-14
299 2021-10-27
210 2021-07-30
294 2021-10-22
101 2021-04-12
221 2021-08-10
140 2021-05-21
142 2021-05-23
199 2021-07-19
59  2021-03-01
293 2021-10-21
302 2021-10-30
254 2021-09-12
68  2021-03-10
332 2021-11-29
113 2021-04-24
191 2021-07-11
..         ...
197 2021-07-17
243 2021-09-01
115 2021-04-26
265 2021-09-23
72  2021-03-14
333 2021-11-30
25  2021-01-26
165 2021-06-15
337 2021-12-04
350 2021-12-17
174 2021-06-24
352 2021-12-19
39  2021-02-09
193 2021-07-13
314 2021-11-11
88  2021-03-30
70  2021-03-12
87  2021-03-29
292 2021-10-20
242 2021-08-31
277 2021-10-05
211 2021-07-31
9   2021-01-10
195 2021-07-15
251 2021-09-09
323 2021-11-20
192 2021-07-12
117 2021-04-28
47  2021-02-17
172 2021-06-22

[365 rows x 1 columns]